// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaPcvQt___aEp9icV5TTmsYElBph-lYbQ',
    appId: '1:351808083112:web:1e9dc8126d45dedfecde9d',
    messagingSenderId: '351808083112',
    projectId: 'english-listening-2a899',
    authDomain: 'english-listening-2a899.firebaseapp.com',
    storageBucket: 'english-listening-2a899.firebasestorage.app',
    measurementId: 'G-CV7H95LFV5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfGlGSXH2SxXY6USpIPjAlnHk5KoT9ynU',
    appId: '1:351808083112:android:50c5c749e4d51994ecde9d',
    messagingSenderId: '351808083112',
    projectId: 'english-listening-2a899',
    storageBucket: 'english-listening-2a899.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCc5AHaEjgQYQHwhNsGSiCItIRnleuKLRE',
    appId: '1:351808083112:ios:f3ddec71a203ccdcecde9d',
    messagingSenderId: '351808083112',
    projectId: 'english-listening-2a899',
    storageBucket: 'english-listening-2a899.firebasestorage.app',
    iosBundleId: 'com.example.englishListening',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCc5AHaEjgQYQHwhNsGSiCItIRnleuKLRE',
    appId: '1:351808083112:ios:f3ddec71a203ccdcecde9d',
    messagingSenderId: '351808083112',
    projectId: 'english-listening-2a899',
    storageBucket: 'english-listening-2a899.firebasestorage.app',
    iosBundleId: 'com.example.englishListening',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCaPcvQt___aEp9icV5TTmsYElBph-lYbQ',
    appId: '1:351808083112:web:b18f50dc3cec7e33ecde9d',
    messagingSenderId: '351808083112',
    projectId: 'english-listening-2a899',
    authDomain: 'english-listening-2a899.firebaseapp.com',
    storageBucket: 'english-listening-2a899.firebasestorage.app',
    measurementId: 'G-W1PLYW8473',
  );
}
